### ISSUE TITLE
Chargement infini (API Hydro inaccessible)

### ISSUE THREAD

**Issue by Maxens63** [grenagit/MMM-VigiCrues#2]
Depuis le 26 juin 2022, vigicrue ne s'affiche plus... 
ça affiche "chargement"

**Comment by grenagit** [comment]
Bonsoir @Maxens63,

L'[API Hydro](https://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr) d'où les données sont récupérées **est inaccessible**, ce n'est donc pas un problème de MMM-VigiCrues ni de MagicMirror !

Avant d'étudier la possibilité de récupérer les données depuis l'[API Vigicrues béta](https://www.vigicrues.gouv.fr/services/1/#faq-2), j'ai ajouté un **message d'erreur** plus **explicite** et **visible** sans avoir à consulter [la console](https://firefox-source-docs.mozilla.org/devtools-user/browser_console/index.html).
